# Generated by Django 4.2 on 2024-04-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_delete_itemlike'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like_products',
            field=models.ManyToManyField(related_name='like_items', to='items.item'),
        ),
    ]
