# Generated by Django 4.2 on 2024-04-17 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_remove_image_item_item_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='item_images', to='items.item'),
        ),
    ]
