# Generated by Django 4.2 on 2024-04-19 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_hashtag_item_hash_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='hash_tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_hashtags', to='items.hashtag'),
        ),
    ]
